server:
  port: 8081
#
#spring:
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#  redis:
#    host: ${SPRING_REDIS_HOST}
#    port: ${SPRING_REDIS_PORT}
#  # snake_case to camelCase
#  jackson:
#    property-naming-strategy: SNAKE_CASE


# local development database setting
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fcfs
    username: root
    password: 2203
  # snake_case to camelCase
  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret:
    key: SW1Hb25uYUJlV29ybGRCZXN0UHJvZ3JhbW1lckFuZElNZWFuSXQ=